pipeline{
    agent {
        label 'agent-1'
    }
    environment{
        appversion=''
        REGION="us-east-1"
        ACCOUNT_NO="430774481266"
        PROJECT="roboshop"
        COMPONENT="catalogue"
    }
    options {
                // timeout(time: 10, unit: 'SECONDS') 
                disableConcurrentBuilds()
                
    }
    /* parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

    } */

    stages{
        stage('Init Stage') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                       sh """
                            cd 00-vpc
                            terraform init -reconfigure
                       """
                    }
                }
            }
        }
        stage('Plan Stage') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                       sh """
                            cd 00-vpc
                            terraform plan
                       """
                    }
                }
            }
        }
        stage('Apply Stage') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"        
            }
            steps {
                 script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                       sh """
                            cd 00-vpc
                            terraform apply -auto-approve
                       """
                    }
                }
            }
        }
 
    }
    post {
        always {
            deleteDir()
        }
 }
}